### ISSUE TITLE
cannot build project in the 1.5 branch

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/client-go#21]
Trying to build in the 1.5 branch (and [directory](https://github.com/kubernetes/client-go/tree/4e647cdbb29217f9f0855caeaab354e7f19d7e42/1.5)) gives me this:

```bash
> ~/Development/client-go/src/k8s.io/client-go/1.5 # go build ./...
kubernetes/typed/core/v1/fake/fake_core_client.go:66: cannot use FakePods literal (type *FakePods) as type "k8s.io/client-go/1.5/kubernetes/typed/core/v1".PodInterface in return argument:
	*FakePods does not implement "k8s.io/client-go/1.5/kubernetes/typed/core/v1".PodInterface (missing Evict method)
```

On master, things are working fine.

/cc @caesarxuchao

**Comment by timoreimann** [comment]
This is fixed. Closing.
