### ISSUE TITLE
Unable to build k8s.io/client-go/tools/clientcmd

### ISSUE THREAD

**Issue by jtestard** [kubernetes/client-go#787]
Building the `k8s.io/client-go/tools/clientcmd` package results in the following error:

```
../../../../../../pkg/mod/k8s.io/client-go@v0.17.0/tools/clientcmd/validation.go:73:5:
cannot use errConfigurationInvalid literal (type errConfigurationInvalid) as type 

"k8s.io/apimachinery/pkg/util/errors".Aggregate in assignment:

        errConfigurationInvalid does not implement "k8s.io/apimachinery/pkg/util/errors".Aggregate (missing Is method)
```

On Feb 11th 2020,  the [kubernetes/apimachinery repository was updated with a change on the stable branch](https://github.com/kubernetes/apimachinery/commit/58692fc9a9fb4926dcc14d369953b305c44625de) in which the `Aggregate` interface was updated with an extra function, thus `errConfigurationInvalid` no longer implements the interface.

**Comment by jtestard** [comment]
I've made a fork in which I fixed this in a very basic way. Haven't gone around doing a PR yet: https://github.com/jtestard/client-go

**Comment by ciiiii** [comment]
I use `k8s.io/client-go v0.17.0` too, and have the same question.

**Comment by liggitt** [comment]
The linked commit is on master and v0.19.0 alpha versions, not on a stable branch. Using a version of k8s.io/apimachinery that matches your client-go version will build properly. For example to use v0.17.0 of client-go, build with v0.17.0 of apimachinery as well.

**Comment by ciiiii** [comment]
@jtestard I tried to use your fix repo, there seem an error
[link](https://github.com/jtestard/client-go/blob/bd2563c407150dc28f51710da9c65e5cc91fde95/tools/clientcmd/validation.go#L112)
![image](https://user-images.githubusercontent.com/28784251/80298298-61f16480-87bd-11ea-9cc8-f9cedfebc8ea.png)
