### ISSUE TITLE
VersionedParams(&listOptions, scheme.ParameterCodec).Timeout(timeout).Body(options).Do have () want (context.Context)

### ISSUE THREAD

**Issue by lolin9** [kubernetes/client-go#794]
A big mess is happening for me after updating from v0.17 to v0.18 and cannot build the binary.

```
pkg/api/clientset/versioned/typed/myapi/v1alpha1/{resource_plural}.go:66:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("{resource_plural}").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
 	have ()
 	want (context.Context)

```

where `resource_plural` is the plural name of each resource. Is this related to here or the code generator `client-gen` that can't generate the correct code?

**Comment by lolin9** [comment]
Yes it seems it was related to client-gen. The solution is to clean the old code generator binaries and build them again with v0.18.
