### ISSUE TITLE
client-go 9.0 does not work with apimachinery 1.12.2

### ISSUE THREAD

**Issue by qiujian16** [kubernetes/client-go#532]
```
# github.ibm.com/IBMPrivateCloud/hcmctl/vendor/k8s.io/client-go/transport/spdy
vendor/k8s.io/client-go/transport/spdy/spdy.go:41:45: not enough arguments in call to spdy.NewRoundTripper
	have (*tls.Config, bool)
	want (*tls.Config, bool, bool)
```

Seems apimachinery change round tripper interface in pkg/util/httpstream/spdy/roundtripper.go after 1.12.2

**Comment by nikhita** [comment]
client-go v9.0.0 will work only with 1.12.0. It is the same as the tag https://github.com/kubernetes/client-go/tree/kubernetes-1.12.0.

For 1.12.2, please use https://github.com/kubernetes/client-go/tree/kubernetes-1.12.2.

/close

**Comment by Cloudzp** [comment]
How can I use client-go with gomodule?Why can't it work?
![image](https://user-images.githubusercontent.com/25190767/50350111-f5d37080-0578-11e9-8440-4d3a172f54e5.png)

![image](https://user-images.githubusercontent.com/25190767/50350129-071c7d00-0579-11e9-9ed9-084aaa1ecdda.png)
